package workshop;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class ExportPagesData {

    public static void main(String[] args) throws IOException {
        String buildVersion = envOrDefault("BUILD_VERSION", "local");
        String commit = envOrDefault("GITHUB_SHA", "unknown");
        String repo = envOrDefault("GITHUB_REPOSITORY", "unknown/repo");

        // Always write into ./docs relative to current working directory
        Path docsDir = Path.of("docs");
        Files.createDirectories(docsDir);

        String json = """
                {
                  "buildVersion": "%s",
                  "commit": "%s",
                  "repository": "%s",
                  "message": "Build metadata generated by ExportPagesData"
                }
                """.formatted(buildVersion, commit, repo);

        Files.writeString(docsDir.resolve("data.json"), json, StandardCharsets.UTF_8);

        String html = """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>CI/CD Workshop</title>
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                </head>
                <body>
                  <h1>CI/CD Workshop Build</h1>
                  <p>Build version: %s</p>
                  <p>Commit: %s</p>
                  <p>Repository: %s</p>
                  <p>See data.json for structured data.</p>
                </body>
                </html>
                """.formatted(buildVersion, commit, repo);

        Files.writeString(docsDir.resolve("index.html"), html, StandardCharsets.UTF_8);
    }

    private static String envOrDefault(String key, String defaultValue) {
        String value = System.getenv(key);
        return (value == null || value.isBlank()) ? defaultValue : value;
    }
}
